---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Authentication
      consumes:
      - application/json
      parameters:
      - name: login
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Login succesfully
        '401':
          description: Login invalid - No proper credentials
  "/api/users/{user_id}/posts":
    get:
      summary: Posts of a specific user
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: user_id
        in: path
        type: string
        required: true
      - name: Authorization
        in: headers
        type: string
      responses:
        '200':
          description: Posts Found
          schema:
            type: array
            properties:
              id:
                type: integer
              author_id:
                type: integer
              title:
                type: string
              text:
                type: text
              likes_counter:
                type: integer
              created_at:
                type: datetime
              updated_at:
                type: datetime
            required:
            - id
            - author_id
            - title
            - text
            - likes_counter
            - created_at
            - updated_at
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
    api_key:
      type: apiKey
      name: api_key
      in: query
